# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_in.setGeometry(QtCore.QRect(950, 500, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_zoom_in.setFont(font)
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.btn_zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_out.setGeometry(QtCore.QRect(1060, 500, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_zoom_out.setFont(font)
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 901, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 897, 597))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(0, 0, 897, 597))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.label)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_img_shape_original = QtWidgets.QLabel(self.centralwidget)
        self.label_img_shape_original.setGeometry(QtCore.QRect(950, 570, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_img_shape_original.setFont(font)
        self.label_img_shape_original.setObjectName("label_img_shape_original")
        self.slider_zoom = QtWidgets.QSlider(self.centralwidget)
        self.slider_zoom.setGeometry(QtCore.QRect(950, 540, 201, 22))
        self.slider_zoom.setMinimum(1)
        self.slider_zoom.setMaximum(100)
        self.slider_zoom.setProperty("value", 50)
        self.slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.slider_zoom.setObjectName("slider_zoom")
        self.label_img_ratio = QtWidgets.QLabel(self.centralwidget)
        self.label_img_ratio.setGeometry(QtCore.QRect(1170, 530, 91, 41))
        self.label_img_ratio.setObjectName("label_img_ratio")
        self.label_img_shape_current = QtWidgets.QLabel(self.centralwidget)
        self.label_img_shape_current.setGeometry(QtCore.QRect(950, 600, 301, 31))
        self.label_img_shape_current.setObjectName("label_img_shape_current")
        self.btn_open_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_image.setGeometry(QtCore.QRect(1060, 60, 93, 28))
        self.btn_open_image.setObjectName("btn_open_image")
        self.label_text_file = QtWidgets.QLabel(self.centralwidget)
        self.label_text_file.setGeometry(QtCore.QRect(940, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_text_file.setFont(font)
        self.label_text_file.setObjectName("label_text_file")
        self.btn_save_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_image.setGeometry(QtCore.QRect(950, 100, 93, 28))
        self.btn_save_image.setObjectName("btn_save_image")
        self.btn_save_as_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_as_image.setGeometry(QtCore.QRect(1060, 100, 93, 28))
        self.btn_save_as_image.setObjectName("btn_save_as_image")
        self.label_text_scale = QtWidgets.QLabel(self.centralwidget)
        self.label_text_scale.setGeometry(QtCore.QRect(940, 460, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text_scale.setFont(font)
        self.label_text_scale.setObjectName("label_text_scale")
        self.spacer_file_resize = QtWidgets.QLabel(self.centralwidget)
        self.spacer_file_resize.setGeometry(QtCore.QRect(950, 130, 311, 16))
        self.spacer_file_resize.setObjectName("spacer_file_resize")
        self.spacer_resize_painter = QtWidgets.QLabel(self.centralwidget)
        self.spacer_resize_painter.setGeometry(QtCore.QRect(950, 220, 311, 16))
        self.spacer_resize_painter.setObjectName("spacer_resize_painter")
        self.label_text_painter = QtWidgets.QLabel(self.centralwidget)
        self.label_text_painter.setGeometry(QtCore.QRect(940, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text_painter.setFont(font)
        self.label_text_painter.setObjectName("label_text_painter")
        self.label_click_current_pos = QtWidgets.QLabel(self.centralwidget)
        self.label_click_current_pos.setGeometry(QtCore.QRect(40, 630, 301, 31))
        self.label_click_current_pos.setObjectName("label_click_current_pos")
        self.label_click_real_pos = QtWidgets.QLabel(self.centralwidget)
        self.label_click_real_pos.setGeometry(QtCore.QRect(340, 630, 301, 31))
        self.label_click_real_pos.setObjectName("label_click_real_pos")
        self.btn_paint_point = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paint_point.setGeometry(QtCore.QRect(950, 280, 93, 28))
        self.btn_paint_point.setObjectName("btn_paint_point")
        self.btn_paint_line = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paint_line.setEnabled(True)
        self.btn_paint_line.setGeometry(QtCore.QRect(1060, 280, 93, 28))
        self.btn_paint_line.setObjectName("btn_paint_line")
        self.btn_paint_curve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paint_curve.setEnabled(True)
        self.btn_paint_curve.setGeometry(QtCore.QRect(1170, 280, 93, 28))
        self.btn_paint_curve.setObjectName("btn_paint_curve")
        self.btn_new_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_new_image.setGeometry(QtCore.QRect(950, 60, 93, 28))
        self.btn_new_image.setObjectName("btn_new_image")
        self.spin_color_red = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_color_red.setGeometry(QtCore.QRect(1020, 330, 71, 22))
        self.spin_color_red.setMaximum(255)
        self.spin_color_red.setProperty("value", 0)
        self.spin_color_red.setObjectName("spin_color_red")
        self.label_painter_colorR = QtWidgets.QLabel(self.centralwidget)
        self.label_painter_colorR.setGeometry(QtCore.QRect(960, 320, 61, 41))
        self.label_painter_colorR.setObjectName("label_painter_colorR")
        self.label_painter_colorG = QtWidgets.QLabel(self.centralwidget)
        self.label_painter_colorG.setGeometry(QtCore.QRect(960, 360, 58, 41))
        self.label_painter_colorG.setObjectName("label_painter_colorG")
        self.label_painter_colorB = QtWidgets.QLabel(self.centralwidget)
        self.label_painter_colorB.setGeometry(QtCore.QRect(960, 400, 58, 41))
        self.label_painter_colorB.setObjectName("label_painter_colorB")
        self.spin_color_green = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_color_green.setGeometry(QtCore.QRect(1020, 370, 71, 22))
        self.spin_color_green.setMaximum(255)
        self.spin_color_green.setObjectName("spin_color_green")
        self.spin_color_blue = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_color_blue.setGeometry(QtCore.QRect(1020, 410, 71, 22))
        self.spin_color_blue.setMaximum(255)
        self.spin_color_blue.setObjectName("spin_color_blue")
        self.label_painter_size = QtWidgets.QLabel(self.centralwidget)
        self.label_painter_size.setGeometry(QtCore.QRect(1130, 320, 58, 41))
        self.label_painter_size.setObjectName("label_painter_size")
        self.spin_size = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_size.setGeometry(QtCore.QRect(1180, 330, 71, 22))
        self.spin_size.setMinimum(1)
        self.spin_size.setMaximum(30)
        self.spin_size.setProperty("value", 5)
        self.spin_size.setObjectName("spin_size")
        self.spacer_painter_scale = QtWidgets.QLabel(self.centralwidget)
        self.spacer_painter_scale.setGeometry(QtCore.QRect(950, 440, 311, 16))
        self.spacer_painter_scale.setObjectName("spacer_painter_scale")
        self.label_text_resize = QtWidgets.QLabel(self.centralwidget)
        self.label_text_resize.setGeometry(QtCore.QRect(940, 150, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_text_resize.setFont(font)
        self.label_text_resize.setObjectName("label_text_resize")
        self.label_resize_percentage = QtWidgets.QLabel(self.centralwidget)
        self.label_resize_percentage.setGeometry(QtCore.QRect(960, 180, 121, 41))
        self.label_resize_percentage.setObjectName("label_resize_percentage")
        self.edit_resize = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_resize.setGeometry(QtCore.QRect(1080, 190, 61, 22))
        self.edit_resize.setMaxLength(3)
        self.edit_resize.setObjectName("edit_resize")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Drawer"))
        self.btn_zoom_in.setText(_translate("MainWindow", "zoom in"))
        self.btn_zoom_out.setText(_translate("MainWindow", "zoom out"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_img_shape_original.setText(_translate("MainWindow", "Original img shape = (1024, 768)"))
        self.label_img_ratio.setText(_translate("MainWindow", "Ratio:100%"))
        self.label_img_shape_current.setText(_translate("MainWindow", "Current img shape = (1024, 768)"))
        self.btn_open_image.setText(_translate("MainWindow", "open file"))
        self.label_text_file.setText(_translate("MainWindow", "File"))
        self.btn_save_image.setText(_translate("MainWindow", "save file"))
        self.btn_save_as_image.setText(_translate("MainWindow", "save as ..."))
        self.label_text_scale.setText(_translate("MainWindow", "Scale Image (Unchange Real Size)"))
        self.spacer_file_resize.setText(_translate("MainWindow", "--------------------------------------------------------------"))
        self.spacer_resize_painter.setText(_translate("MainWindow", "--------------------------------------------------------------"))
        self.label_text_painter.setText(_translate("MainWindow", "Painter"))
        self.label_click_current_pos.setText(_translate("MainWindow", "Current mouse pos = (0, 0)"))
        self.label_click_real_pos.setText(_translate("MainWindow", "Real mouse pos = (0, 0)"))
        self.btn_paint_point.setText(_translate("MainWindow", "point"))
        self.btn_paint_line.setText(_translate("MainWindow", "line"))
        self.btn_paint_curve.setText(_translate("MainWindow", "curve"))
        self.btn_new_image.setText(_translate("MainWindow", "new file"))
        self.label_painter_colorR.setText(_translate("MainWindow", "Red :"))
        self.label_painter_colorG.setText(_translate("MainWindow", "Green :"))
        self.label_painter_colorB.setText(_translate("MainWindow", "Blue :"))
        self.label_painter_size.setText(_translate("MainWindow", "Size :"))
        self.spacer_painter_scale.setText(_translate("MainWindow", "--------------------------------------------------------------"))
        self.label_text_resize.setText(_translate("MainWindow", "Resize Image (Change Real Size)"))
        self.label_resize_percentage.setText(_translate("MainWindow", "Percentage(%) :"))
        self.edit_resize.setText(_translate("MainWindow", "100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

