# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_in.setGeometry(QtCore.QRect(930, 180, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_zoom_in.setFont(font)
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.btn_zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_out.setGeometry(QtCore.QRect(1040, 180, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_zoom_out.setFont(font)
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 901, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 897, 597))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(0, 0, 897, 597))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.label)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label_img_shape_original = QtWidgets.QLabel(self.centralwidget)
        self.label_img_shape_original.setGeometry(QtCore.QRect(930, 260, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_img_shape_original.setFont(font)
        self.label_img_shape_original.setObjectName("label_img_shape_original")
        self.slider_zoom = QtWidgets.QSlider(self.centralwidget)
        self.slider_zoom.setGeometry(QtCore.QRect(930, 230, 201, 22))
        self.slider_zoom.setMinimum(1)
        self.slider_zoom.setMaximum(100)
        self.slider_zoom.setProperty("value", 50)
        self.slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.slider_zoom.setObjectName("slider_zoom")
        self.label_img_ratio = QtWidgets.QLabel(self.centralwidget)
        self.label_img_ratio.setGeometry(QtCore.QRect(1150, 220, 111, 41))
        self.label_img_ratio.setObjectName("label_img_ratio")
        self.label_img_shape_current = QtWidgets.QLabel(self.centralwidget)
        self.label_img_shape_current.setGeometry(QtCore.QRect(930, 290, 301, 31))
        self.label_img_shape_current.setObjectName("label_img_shape_current")
        self.btn_open_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_image.setGeometry(QtCore.QRect(930, 60, 93, 28))
        self.btn_open_image.setObjectName("btn_open_image")
        self.label_text_file = QtWidgets.QLabel(self.centralwidget)
        self.label_text_file.setGeometry(QtCore.QRect(930, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text_file.setFont(font)
        self.label_text_file.setObjectName("label_text_file")
        self.btn_save_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_image.setGeometry(QtCore.QRect(1040, 60, 93, 28))
        self.btn_save_image.setObjectName("btn_save_image")
        self.btn_save_as_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_as_image.setGeometry(QtCore.QRect(1150, 60, 93, 28))
        self.btn_save_as_image.setObjectName("btn_save_as_image")
        self.label_text_scale = QtWidgets.QLabel(self.centralwidget)
        self.label_text_scale.setGeometry(QtCore.QRect(930, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_text_scale.setFont(font)
        self.label_text_scale.setObjectName("label_text_scale")
        self.spacer_file = QtWidgets.QLabel(self.centralwidget)
        self.spacer_file.setGeometry(QtCore.QRect(930, 100, 311, 16))
        self.spacer_file.setObjectName("spacer_file")
        self.spacer_scale = QtWidgets.QLabel(self.centralwidget)
        self.spacer_scale.setGeometry(QtCore.QRect(930, 330, 311, 16))
        self.spacer_scale.setObjectName("spacer_scale")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_zoom_in.setText(_translate("MainWindow", "zoom in"))
        self.btn_zoom_out.setText(_translate("MainWindow", "zoom out"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_img_shape_original.setText(_translate("MainWindow", "Original img shape = (1024, 768)"))
        self.label_img_ratio.setText(_translate("MainWindow", "Ratio:100%"))
        self.label_img_shape_current.setText(_translate("MainWindow", "Current img shape = (1024, 768)"))
        self.btn_open_image.setText(_translate("MainWindow", "open file"))
        self.label_text_file.setText(_translate("MainWindow", "File"))
        self.btn_save_image.setText(_translate("MainWindow", "save file"))
        self.btn_save_as_image.setText(_translate("MainWindow", "save as ..."))
        self.label_text_scale.setText(_translate("MainWindow", "Scale Image"))
        self.spacer_file.setText(_translate("MainWindow", "--------------------------------------------------------------"))
        self.spacer_scale.setText(_translate("MainWindow", "--------------------------------------------------------------"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

